import React from 'react';
import socketjuice_full_logo from "../../images/SocketJuice.png"
import { Link } from 'react-router-dom';

export default function PrivacyPage(){


    return (

        <>
        <div className='w-full flex-col px-6 sm:px-8 md:px-10 py-10 justify-center items-center
            rounded-xl md:rounded-none shadow-inner md:shadow-none'>

            <div className='flex items-center justify-center px-10 pb-6'>
                <Link to={"/map"} className='flex flex-col'>
                    <img className='w-[350px]' src={socketjuice_full_logo} />
                </Link>
            </div>
        
            <div className='flex items-center justify-center px-10'>
                <p className='text-3xl'>Privacy Policy</p>    
            </div>

            <div className='mt-8'>
                <p className='text-center text-xl font-bold underline py-2'>Last Revised: December 2, 2023</p>
                <p className='text-center text-xl font-semibold pt-2'> Definitions and Services Overview </p>
                <p className='text-base break-words text-justify pb-2'>SocketJuice, “we”, “We”, “us”, and “the website” will refer to www.socketjuice.com and subsidiaries including all applications. </p>
                <p className='text-base break-words text-justify pb-2'> SocketJuice is an online tool for owners of electric vehicles to share their electric charging equipment in order to earn extra money. The SocketJuice website, applications, and associated services are collectively referred to as “the Services”. SocketJuice and its subsidiaries care about privacy and want you to be familiar with how we collect, use, process, and disclose your personal information. This Privacy Policy describes our privacy practices in connection with our websites and applications that link to this Privacy Policy and our offline interactions with you in settings where we post this Privacy Policy.
                </p>

                <p className='text-center text-xl font-semibold pt-2'> Data that you submit to us </p>
                <p className='text-base break-words text-justify pb-2'> When you register for an account with us, we require certain personal information to open your account, such as your name, email address, and password. </p>
                <p className='text-base break-words text-justify pb-2'> We may also ask you to provide additional profile information to use certain features of the Services which may include street addresses, phone numbers, license plate number, driver’s license number, profile photos, city, biography, and date of birth. Certain parts of your profile (like your profile photos, city, and biography) are part of your public profile page and will be publicly visible to others. </p>
                <p className='text-base break-words text-justify pb-2'> We may collect your digital payment details, bank account or payment card numbers, and transaction information in connection with a potential or actual transaction, which may be processed and stored by one or more third party payment service providers or digital payments companies. </p>
                <p className='text-base break-words text-justify pb-2'> In some instances, we may collect identity verification information such as a photograph or scanned copy of a driver’s license, license plate, social media account information, driver’s/motor vehicle record, or other forms of identification information. Where we request that you withhold certain information (such as obscuring or redacting aspects of identification information), please do so. </p>
                <p className='text-base break-words text-justify pb-2'> When you communicate with SocketJuice, including via phone, email, or chat, or use the Services to communicate with other users, we may collect information about your communication and any information you choose to provide. </p>
                <p className='text-base break-words text-justify pb-2'> We collect information you provide when you choose to participate in user research initiatives and/or community surveys. This may include demographic information if you choose to share it with us. </p>
                <p className='text-center text-xl font-semibold pt-2'> Data that we collect directly from users </p>
                <p className='text-base break-words text-justify pb-2'> We collect information about your interactions with the Services, such as the pages or other content you view, your log-in history, your searches, bookings you have made, how long you spent on a page or screen, sites from which you link or browse to in the Services, navigation paths between pages or screens, information about your activity on a page or screen, access time, duration of access, and other actions on the Services. </p>
                <p className='text-base break-words text-justify pb-2'> When you use certain features of the Services, we may collect information about your approximate location (e.g., city/town associated with your IP address). When you opt in to use our location sharing feature, we may collect the precise location information of your mobile device. Keep in mind that most mobile devices allow you to control or disable the use of location services by any application on your mobile device in the device’s settings menu. </p>
                <p className='text-base break-words text-justify pb-2'> We may collect information about your computer or mobile device, such as its operating system type and version number, manufacturer and model, browser type, screen resolution, IP address, unique device identifiers, or general location information such as city, state, or geographic area. </p>
                <p className='text-base break-words text-justify pb-2'> We collect transactional information related to the reservations you make through the Services, including the date and time of your reservation, amounts charged, and other related reservation details. </p>
                <p className='text-base break-words text-justify pb-2'> When you access the Services, we (including companies we work with) may place small data files on your computer or other device. These data files may be cookies, clear gifs, pixel tags, e-tags, “Flash cookies”, or other local storage provided by your browser or associated applications (collectively “Cookies”).  </p>
                <p className='text-center text-xl font-semibold pt-2'> Data that we collect from third-party sources </p>
                <p className='text-base break-words text-justify pb-2'> If you choose to log in to our Services through a third-party site or service (e.g., Apple, Facebook, or Google), the third-party service may send us information such as your registration and profile information from that service. The information we may receive varies by service and is controlled by the relevant service. By associating an account managed by a third party with your SocketJuice account and authorizing SocketJuice to have access to this information, you agree that SocketJuice may collect, store, and use this information in accordance with this Privacy Policy. We are not responsible for how those third parties use and share your information. Please refer to the privacy policies of those third parties to understand how they use and share your personal information. </p>
                <p className='text-base break-words text-justify pb-2'>To the extent permitted by applicable laws, SocketJuice may collect background information about you from public records, background check providers, or other screening services, including credit reports and information about criminal convictions or from sex offender registries. </p>

                <p className='text-base break-words text-justify pb-2'> To the extent permitted by applicable law, we may receive additional information about you, such as demographic data, fraud detection information, or data from credit bureaus and other third-party data providers. We may combine the information about you that we receive from third-party sources with other information we have about you. </p>
                <p className='text-center text-xl font-semibold pt-2'> Usage of your data at SocketJuice</p>
                <p className='text-center text-lg font-semibold pt-2'> Operational Data Needs</p>
                <p className='text-base break-words text-justify pb-2'> We use, store, and process your personal information to provide and improve the Services during operations and for security and safety purposes. For example, we may use your information to: (1) provide and operate the Services, (2) provide customer support, (3) send you service, support, and administrative messages, reminders, technical notices, updates, security alerts, and information requested by you at any telephone number, by placing a voice call or through text (SMS) or email messaging, (4) facilitate your login to the Services via third-party identity and access management providers, such as Facebook, Google, and Apple, (5) process transactions and send notices about your transactions, (6) personalize or customize your user experience, (7), enable you to communicate with other SocketJuice users, including by sending them messages or other information during the booking process, (8) facilitate your referral invitations, (9) send your requests for reviews, for fraud detection and prevention, and for any purpose you authorize at the time of collection, (10) administer referral programs, rewards, surveys, contests, or other promotional activities or sponsored events in which you participate. </p>
                <p className='text-center text-lg font-semibold pt-2'> For research and development</p>
                <p className='text-base break-words text-justify pb-2'> We may use your personal information to analyze and improve the Services and to develop new products and services, including by studying our user demographics of the Services. We may also create aggregated, de-identified, or other anonymous data from your personal information. We make personal information into anonymous data by removing information that makes the data personally identifiable to you. We may use this anonymous data and share it with third parties for our lawful business purposes, including to analyze and improve the Services and promote our business. </p>
                <p className='text-center text-lg font-semibold pt-2'> For marketing and advertising</p>
                <p className='text-base break-words text-justify pb-2'>We and our third party advertising partners may collect and use your personal information for marketing and advertising purposes. We may contract with third party advertising and social media companies to display ads on the Services and other sites. These companies may use cookies and similar technologies to collect information about you (including the device data, online activity data, and/or geolocation data described above) over time across our Services and other sites and services or your interaction with our emails, and use that information to serve ads that they think will interest you. These ads are known as “interest-based advertisements”. You can learn more about your choices for limiting interest-based advertising in the appropriate section below. </p>
                <p className='text-center text-lg font-semibold pt-2'> For security and safety </p>
                <p className='text-base break-words text-justify pb-2'> We may use your data to (1) verify your identity or authenticate information that you provide, including during account creation and password reset processes, (2) resolve disputes, collect fees, and troubleshoot problems, (3) detect, prevent, and/or remediate fraud, abuse, security incidents, or other potentially harmful, prohibited, or illegal activities, (4) detect, prevent, or remediate violations of and enforce our Terms of Service and Privacy Policy, (5) manage and protect our information technology infrastructure, (6) conduct investigations and risk assessments, (7) conduct checks against databases and information sources (such as but not limited to public government databases), (8) perform creditworthiness and solvency checks</p>
                <p className='text-center text-lg font-semibold pt-2'> For legal and compliance </p>
                <p className='text-base break-words text-justify pb-2'>We use your personal information as we believe necessary or appropriate to comply with applicable laws, lawful requests, and legal processes, such as to respond to subpoenas or requests from government authorities. </p>

                <p className='text-center text-xl font-semibold pt-2'> Disclosure and Sharing of Data</p>

                <p className='text-center text-lg font-semibold pt-2'> Profiles, listings, search results, and other public information</p>
                <p className='text-base break-words text-justify pb-2'> By agreeing to this privacy policy, we have your consent to share your information on the Services. Your public listing page on the Services will always include some basic information, such as your user ID or name associated with your account, your public profile photo, and for hosts, your listing description such as what type of charging equipment you are offering, your calendar availability, transaction related information to allow our community to evaluate your reliability and responsiveness, and reviews or feedback about you. Your public listing page may also include aggregate demand information (such as number of page views over a period of time) and information about your cancellations. The Service will also provide and display the approximate geographic pick-up location of your charging equipment. The Services allow your public profile and public listing to be included in search engines, in which case your public profile and public listing pages may be indexed by search engines and may be published as search results. </p>
                <p className='text-center text-lg font-semibold pt-2'> Sharing between hosts and drivers </p>
                <p className='text-base break-words text-justify pb-2'> SocketJuice enables owners of charging equipment to offer and share their charging equipment with other individuals. If you agree to a booking through the Services, we may provide your information to the other party in that transaction as reasonably necessary to facilitate the transaction. For example, SocketJuice may provide your mobile phone number to facilitate communication, your license plate or driver's license information to confirm license validity and for identity verification, or your photograph to facilitate identification. We will also share the address of the charging equipment and, if applicable, the proposed delivery location with the other party. The other party may also send you text messages (such as to confirm location), subject to standard charges from your telecom provider. </p>
                <p className='text-center text-lg font-semibold pt-2'> Service providers </p>
                <p className='text-base break-words text-justify pb-2'>We may share information with vendors and service providers who support the operation of the Services and business and who need access to such information to carry out their work for us (including, for example, web hosting, analytics, payment processing, email delivery, marketing, property recovery, incident response, and customer support services). In some cases, the service provider may directly collect the information from you on our behalf. </p>
                <p className='text-center text-lg font-semibold pt-2'> Professional advisors </p>
                <p className='text-base break-words text-justify pb-2'>We may disclose your personal information to professional advisors, such as lawyers, bankers, auditors, and insurers, where necessary in the course of the professional services that they render to us. </p>
                <p className='text-center text-lg font-semibold pt-2'> Business transfers</p>
                <p className='text-base break-words text-justify pb-2'> We may sell, transfer, or otherwise share some or all of our business or assets, including your personal information, in connection with a business transaction (or potential business transaction) such as a corporate divestiture, merger, consolidation, acquisition, reorganization, or sale of assets, or in the event of bankruptcy or dissolution. </p>
                <p className='text-center text-lg font-semibold pt-2'> Responding to legal requests, preventing harm, and protecting our rights </p>
                <p className='text-base break-words text-justify pb-2'>We may disclose your personal information to courts, law enforcement, governmental or tax authorities, or third parties. We will make such disclosure to the extent we are required or permitted to do so by applicable law or where we consider such disclosure is reasonably necessary to comply with our legal obligations or legal process, to respond to claims asserted against us, and for security and safety purposes previously described.  We may also disclose your information in response to valid legal requests relating to criminal investigations or alleged or suspected illegal activity or any other activity that may expose SocketJuice, you, or any other user, or to protect the rights, property, or personal safety of SocketJuice, our users, or others. We may also disclose your personal information as described elsewhere in this Privacy Policy or as disclosed to you at the time of collection. </p>

                <p className='text-center text-xl font-semibold pt-2'> Your data preferences and choices </p>
                <p className='text-base break-words text-justify pb-2'> Communication preferences </p>
                <p className='text-base break-words text-justify pb-2'> You can control the methods by which we may contact you about your account, your booking and listing activities, promotions, and announcements in the Settings section within your account. </p>

                <p className='text-xl break-words text-justify pb-2'> Communication preferences </p>
                <p className='text-lg break-words text-justify pb-2'> Updating data settings </p>
                <p className='text-base break-words text-justify pb-2'> You can review, correct, update, and edit certain information that has been previously provided to us by you at any time by logging in to your account and reviewing your account settings and profile. You can also access or request a correction of your information by contacting us at support@socketjuice.com. For your protection, we may need to verify your identity before implementing your request.</p>

                <p className='text-lg break-words text-justify pb-2'> Account closure </p>
                <p className='text-base break-words text-justify pb-2'> If you wish to close your account and request deletion of your personal information, please send an email to support@socketjuice.com. Please note that we may be unable to delete information needed to comply with applicable laws, detect or prevent fraud, collect any fees owed, resolve disputes, assist with or process claims, troubleshoot problems, assist with any audits and investigations, to enforce our Terms of Service and Privacy Policy, and take other actions reasonably necessary, permitted, or required by applicable law. There may also be residual information that will remain within our databases and other records, which will not be removed.</p>

                <p className='text-lg break-words text-justify pb-2'> Location data </p>
                <p className='text-base break-words text-justify pb-2'> Users of our mobile application can disable the application’s access to the device’s location within the device’s settings.</p>

                <p className='text-lg break-words text-justify pb-2'> Interest-based advertising choices </p>
                <p className='text-base break-words text-justify pb-2'> You have choices for limiting use of your personal information for interest-based advertising including: (1) You may change your cookie preferences for the SocketJuice website at any time via the cookie preferences link located in the webpage footer, (2) Most browsers let you remove or reject cookies, including cookies used for interest-based advertising. To do this, follow the instructions in your browser settings. Many browsers accept cookies by default until you change your settings. For more information about cookies, including how to see what cookies have been set on your device and how to manage and delete them, visit www.allaboutcookies.org, (3) Your mobile device settings may provide functionality to limit use of the advertising ID associated with your mobile device (e.g., Apple ID for Advertising or Google Advertising ID) for interest-based advertising purposes, (4) You can block sites from setting cookies for interest-based ads by using a browser with privacy features, like Brave, or installing browser plugins like Privacy Badger, Ghostery, or uBlock Origin, and configuring them to block third party cookies/trackers. </p>
                <p className='text-lg break-words text-justify pb-2'> Choosing not to share your personal information </p>
                <p className='text-base break-words text-justify pb-2'>Where we are required by law to collect your personal information, or where we need your personal information in order to provide the Services to you, if you do not provide this information when requested (or we later delete it at your request), we may not be able to provide you with the Services. </p>
                <p className='text-lg break-words text-justify pb-2'> Security Disclosure </p>
                <p className='text-base break-words text-justify pb-2'> We employ a number of technical, physical, and organizational measures designed to protect information against unauthorized access, destruction, or alteration while it is under our control. However, no method of transmitting or storing information can be 100% secure and we cannot guarantee the security of your personal information.</p>
                <p className='text-xl break-words text-justify pb-2'> Other important information </p>
                <p className='text-lg break-words text-justify pb-2'> Cross border transfer </p>
                <p className='text-base break-words text-justify pb-2'> Your personal information may be used, stored, and processed in any country where we have facilities or in which we engage service providers. These locations may be outside of your state, province, or country of residence, and may have different and/or less protective data protection rules than those of your state, province, or country. As a result, this information may be subject to access requests from governments, courts, regulatory agencies, security authorities, or law enforcement in those jurisdictions according to the laws in those jurisdictions.</p>
                <p className='text-lg break-words text-justify pb-2'> Sensitive information </p>
                <p className='text-base break-words text-justify pb-2'> We ask that you not send us, and you not disclose, any sensitive information (e.g., Social Security numbers, social insurance numbers, passports, information related to racial or ethnic origin, or health) on or through the Services or otherwise to us unless specifically requested.</p>
                <p className='text-lg break-words text-justify pb-2'> Minors </p>
                <p className='text-base break-words text-justify pb-2'>The Services are not intended for anyone under the age of 18 and we do not knowingly collect personal information from users under the age of 18. If a minor under the age of 18 has already provided us with personal information, his or her parent or guardian may contact us to request that we delete it. </p>
                <p className='text-lg break-words text-justify pb-2'> Third-party privacy practices</p>

                <p className='text-base break-words text-justify pb-2'>This Privacy Policy addresses only the use and disclosure of information collected by SocketJuice. This Privacy Policy does not address, and we are not responsible for, the privacy, information, or other practices of any third parties, including any third party operating any site or service to which the Services link. The inclusion of a link on the Services does not imply endorsement of the linked site or service by us or by our affiliates. If you disclose your information to others, or if you are directed to a third-party website, their privacy notices and practices will apply. Some areas of the Services implement Google Maps/Places mapping services, including the Google Places API. In addition, to fight spam and abuse of the Services, SocketJuice has implemented reCAPTCHA Enterprise, a Google service. Your use of the Services is subject to Google’s Privacy Policy. </p>
                <p className='text-lg break-words text-justify pb-2'> Translations</p>
                <p className='text-base break-words text-justify pb-2'>Where SocketJuice has provided you with a version of this Privacy Policy in a language other than English, in case of any wording discrepancies between such version and the English version, the English wording takes precedence. </p>
                <p className='text-xl break-words text-justify pb-2'> Changes to this privacy policy </p>
                <p className='text-base break-words text-justify pb-2'>We may change this Privacy Policy. Please take a look at the “Last revised” legend at the top of this page to see when this Privacy Policy was last revised. Any changes to this Privacy Policy will become effective when we post the revised Privacy Policy on the Services or as otherwise indicated. Your use of the Services following these changes means that you accept the revised Privacy Policy. If you don’t agree to these changes, you can contact us to close your account. </p>
            </div>

        </div>
        </>
    )
}