import React from 'react';
import socketjuice_full_logo from "../../images/SocketJuice.png"

export default function TermsPage(){


    return (

        <>
        <div className='w-full flex-col max-w-[700px] px-6 sm:px-8 md:px-10 py-10
            rounded-xl md:rounded-none shadow-inner md:shadow-none'>

            <div className='flex items-center justify-center px-10 pb-6'>
                <img className='w-100' src={socketjuice_full_logo} />
            </div>
        
            <div className='flex items-center justify-center px-10'>
                <p className='text-3xl'>Terms of Service</p>    
            </div>
            
            <div className='mt-8'>
        
                <p className='text-center text-xl font-bold underline py-2'>Last Revised: December 2, 2023</p>
                <p className='text-center text-xl font-semibold pt-2'> Definitions and Services Overview </p>
                <p className='text-base break-words text-justify pb-2'> SocketJuice, “we”, “We”, “us”, and “the website” will refer to www.socketjuice.com and subsidiaries including all applications. SocketJuice is an online tool for owners of electric vehicles to share their electric charging equipment in order to earn extra money. The SocketJuice website, applications, and associated services are collectively referred to as “the Services”. SocketJuice is accessible online including at SocketJuice.com and by accessing or using the website, including by communicating with us or other SocketJuice users, you agree to comply with, and be legally bound by, the provisions of these Terms of Service (these “Terms”), whether or not you become a registered user of the Services. These Terms govern your access to and use of the Services and constitute a binding legal agreement between you and SocketJuice. </p>
                <p className='text-base break-words text-justify pb-2'> By using the SocketJuice website, you agree to the terms of service and take full responsibility and cover all expenses should any damages or accidents occur during usage of SocketJuice or as a result of using SocketJuice. You agree to waive all responsibility and expenses for SocketJuice should any damage or accident occur during your usage of SocketJuice or as a result of using SocketJuice. </p>  
                <p className='text-base break-words text-justify pb-2'> You confirm that you will conduct yourself according to all applicable laws and regulations in your geographic region and you confirm that you are aware that SocketJuice will be in full cooperation with law enforcement should any laws or regulations be broken related to your usage on SocketJuice. </p>  
                <p className='text-base break-words text-justify pb-2'> SocketJuice reserves the right, at our sole discretion, to modify the Services, including these Terms, at any time. If we modify these Terms, we will post the modification on the Services. We will also update the “Last Revised” date at the top of these Terms. If you continue to access or use the Services after we have posted a modification or have provided you with notice of a modification, you are indicating that you agree to be bound by the modified terms. If the modified terms are not acceptable to you, your sole recourse is to stop using and accessing the Services and close your SocketJuice Account within 30 days. If you choose to close your SocketJuice Account, the previous effective version of these Terms will apply to you, unless you use the Services during the intervening 30 day period, in which case the new version of these Terms will apply to you. </p>  

                <p className='text-center text-xl font-semibold pt-2'> Eligibility, registration, verification </p>
                <p className='text-base break-words text-justify pb-2'> The Services are intended solely for individuals who are above the age of 18 or legally verified to drive in their place of residence. Any use of the Services by anyone that does not meet these eligibility requirements is expressly prohibited. </p>
                <p className='text-base break-words text-justify pb-2'> To access certain features of the Services, you must sign up for an account with us (a “SocketJuice Account”). You can create a SocketJuice Account by providing us your first and last name, email address, mobile phone number, and creating a password. You must provide accurate, current, and complete information during the registration process. You must keep your SocketJuice Account up to date at all times. Based on information you provide, SocketJuice may impose additional requirements for you to reserve electric vehicle charging equipment. </p>
                <p className='text-base break-words text-justify pb-2'> Where permitted, SocketJuice has the right, but not the obligation, to undertake screenings, checks, and engage in processes designed to (1) help verify the identities or check the backgrounds of users, including license plate validity and (2) verify the driver’s vehicle details. SocketJuice may in its sole discretion use third-party services to verify the information you provide to us and to obtain additional related information and corrections where applicable, and you hereby authorize SocketJuice to request, receive, use, and store such information. SocketJuice may permit or refuse your request to reserve electric vehicle charging equipment at any time. SocketJuice may, but does not commit to, undertake efforts to ensure the safety and condition of vehicles being charged or the charging equipment being used. We do not make any representations about, confirm, or endorse the safety or legal status of any vehicles or charging equipment. </p>

                <p className='text-center text-xl font-semibold pt-2'> Payments, Fees and Taxes </p>
                <p className='text-base break-words text-justify pb-2'> The cost for reserving charging equipment will be outlined for users as a function of the charging time requested multiplied by the rate that the host of charging equipment will request. You can verify the total cost amount for your reservation at checkout before you submit your reservation request. A history of transactions can be viewed under the settings panel. SocketJuice is not currently storing any payment information from its users on our systems, however, we reserve the right to change this policy at any time in the future. When you provide SocketJuice a payment method, you authorize SocketJuice, or third-party service providers acting on behalf of SocketJuice, to store your payment credential in the future. You authorize SocketJuice to use stored payment credentials for balances. In some cases, our payment processors have arrangements with card networks to automatically update stored payment credentials whenever you receive a new card (e.g., replacing an expired card or one that was reported lost or stolen) and we will rely on such updates to stored payment credentials for balances. </p>
                <p className='text-base break-words text-justify pb-2'>SocketJuice and its service providers will employ all legal methods available to collect amounts due, including the engagement of collection agencies or legal counsel. SocketJuice, or the collection agencies we retain, may also report information about your SocketJuice Account to credit bureaus. As a result, forged payments, missed payments, or other improper credit card usage or defaults on your SocketJuice Account may be reflected in your credit report. In addition to the amount due, delinquent accounts or chargebacks will be charged with fees and/or charges that are incidental to the collection of delinquent accounts or chargebacks including, but not limited to, collection fees, convenience fees, and/or other third party charges. If you wish to dispute the information a collection agency reported to a credit bureau regarding your SocketJuice Account, you must contact the collection agency directly. </p>
                <p className='text-base break-words text-justify pb-2'>In certain jurisdictions, SocketJuice may enable the collection and remittance of certain taxes from or on behalf of hosts, based on existing and future tax regulations, including marketplace facilitator or other regulations. The amount of taxes, if any, collected and remitted by SocketJuice will be visible to, and separately stated, to hosts on their respective invoices. </p>

                <p className='text-center text-xl font-semibold pt-2'> User commitments </p>
                <p className='text-base break-words text-justify pb-2'>You agree that you will always use your SocketJuice Account and the Services in compliance with these Terms, applicable law, and any other policies and standards provided to you by SocketJuice. </p>
                <p className='text-base break-words text-justify pb-2'>You are, and will be solely responsible for, all activity that occurs through your SocketJuice Account. Keep your SocketJuice Account information, including your password, secure. You agree that you will not disclose your password to any third party and that you will take sole responsibility for any activities or actions under your SocketJuice Account, whether you have authorized such activities or actions. You will immediately notify SocketJuice of any actual or suspected unauthorized use of your SocketJuice Account. We are not responsible for your failure to comply with this clause, or for any delay in shutting down or protecting your SocketJuice Account unless you have reported unauthorized access to us. </p>
                <p className='text-center text-xl font-semibold pt-2'> Content </p>
                <p className='text-base break-words text-justify pb-2'> Subject to your compliance with the provisions of these Terms, SocketJuice grants you a limited, revocable, non-exclusive, non-transferable license, to access and view any SocketJuice and/or user content to which you are permitted access, solely for your personal and non-commercial purposes. You have no right to sublicense the license rights granted in this section. No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by SocketJuice or its licensors, except for the licenses and rights expressly granted in these Terms. </p>
                <p className='text-base break-words text-justify pb-2'> Some areas of the Services implement Google Maps/Places mapping services, including Google Places API. In addition, to fight spam and abuse of the Services, SocketJuice has implemented reCAPTCHA Enterprise, a Google service. By using the Services, you are bound by Google's Terms of Service. </p>

                <p className='text-center text-xl font-semibold pt-2'> Prohibited activities </p>
                <p className='text-base break-words text-justify pb-2'>In connection with your use of or access to the Services, you agree that you will not, nor advocate, encourage, request, or assist any third party to: </p>
                <p className='text-base break-words text-justify pb-2'>Violate any law, including: (1) Breach, violate, and/or circumvent any local, state, provincial/territorial, regional, or national law or other law or regulation, or any order of a court, including, without limitation, airport regulations and tax regulations, licensing or registration requirements, or third-party rights. (2) Post false, inaccurate, misleading, defamatory, or libelous content, (3) Infringe, reproduce, perform, display, distribute, reverse engineer, or prepare derivative works from content that belongs to or is licensed to SocketJuice, or that comes from the Services and belongs to another SocketJuice user or to a third party, including works covered by any copyrights, trademark, patent, or other intellectual property, privacy, publicity, moral, or contractual rights, except with prior express written permission of SocketJuice. </p>
                <p className='text-base break-words text-justify pb-2'>Dilute, tarnish, or otherwise harm the SocketJuice brand in any way, including: (1) Through unauthorized use of the Services and/or user content, (2) Registering and/or using "SocketJuice" or derivative terms in domain names, trade names, trademarks, or otherwise, (3) Registering and/or using domain names, trade names, trademarks, social media account names, or other means of identification that closely imitate or are confusingly similar to SocketJuice domains, trademarks, taglines, promotional campaigns, or SocketJuice and/or user content. </p>
                <p className='text-base break-words text-justify pb-2'>Provide false or misleading information, or fail to uphold user responsibilities, including: (1) Providing a false name, license details, payment method, or other personal information, (2) Registering for a SocketJuice Account on behalf of an individual other than yourself or the company you represent, (3) Impersonating any person or entity, or falsifying or otherwise misrepresenting yourself or your affiliation with any person or entity, (4) Failing to pay fees, penalties, or other amounts owed to SocketJuice or another user, (5) Transfer your SocketJuice Account and/or user ID to another party without our consent, (6) Utilize charging equipment in a manner for which it was not intended, or using charging equipment in an unsafe manner</p>
                <p className='text-base break-words text-justify pb-2'> Harm or threaten to harm users of our community, including: (1) Harass, stalk, or defame any other SocketJuice user or collect or store any personally identifiable information about any other user other than for purposes of transacting as a host or driver in accordance with these Terms, (2) Engage in physically or verbally abusive or threatening conduct, (3) Use the Services to transmit, distribute, post, or submit any information concerning any other person or entity, including without limitation, photographs of others without their permission, personal contact information, payment method details, or account numbers, (4) Treat anyone differently based on the way they look, who they love, what they believe, how they self-identify, where they are from, or when they were born. Discrimination of any kind is not tolerated in the SocketJuice community, (5) Sue or assert legal claims against SocketJuice or a SocketJuice user in any manner prohibited or waived by these Terms </p>
                <p className='text-base break-words text-justify pb-2'> Use the Services for your own unrelated purposes, including to: (1) Contact another SocketJuice user for any purpose other than in relation to a reservation booking or the use of the Services by such user, (2) Commercialize any content found on the Services or software associated with the Services, including reviews, (3) Harvest or otherwise collect information about users without their and our consent, (4) Recruit or otherwise solicit any user to join third-party services or websites that are competitive to SocketJuice, without our prior written approval. </p>
                <p className='text-base break-words text-justify pb-2'>Interfere with the operation of the Services, including by: (1) Interfering with any other charging equipment listings belong to another user, , (2) Using the Services in connection with the distribution or posting of unsolicited commercial messages (e.g., spam), (3) Distributing viruses or any other technologies such as cancel bots, Trojan horses, harmful code, flood pings, denial-of-service attacks, backdoors, packet or IP spoofing, forged routing or e-mail address information, or similar methods or technology that may disrupt or interfere with the operation or provision of the Services, or harm SocketJuice or the interests or property of others, (4) Bypassing robot exclusion headers, interfering with the working of the Services, or imposing an unreasonable or disproportionately large load on our infrastructure, (5) Systematically retrieving data or other content from the Services to create or compile, directly or indirectly, a collection, compilation, database, directory, or the like, whether by manual methods, or through the use of bots, crawlers, spiders, or otherwise, (6) Using, displaying, mirroring, or framing the Services or any individual element within the Services, the SocketJuice name, any SocketJuice trademark, logo, or other proprietary information, or the layout and design of any page or form contained on a page in the Services, without the express written consent of SocketJuice, (7) Accessing, tampering with, or using non-public areas of the Services, our computer systems, or the technical delivery systems of our service providers, (8) Attempting to probe, scan, or test the vulnerability of any of our system or network or breach any security or authentication measures, (9) Avoiding, bypassing, removing, deactivating, impairing, descrambling, or otherwise circumventing any technological measure implemented by SocketJuice or any of our service providers or any other third party (including another user) to protect the Services, (10) Forging any TCP/IP packet header or any part of the header information in any email or newsgroup posting , or in any way using the Services to send altered, deceptive, or false source-identifying information, (11) Attempting to decipher, decompile, disassemble, or reverse engineer any of the software used to provide the Services, (12) Endeavoring to circumvent a suspension, termination, or closure of a SocketJuice Account. </p>

                <p className='text-center text-xl font-semibold pt-2'> Other legal matters </p>
                <p className='text-base break-words text-justify pb-2'> SocketJuice has the right, but not the obligation, to investigate, pursue, and seek to prosecute, litigate, or refer to law enforcement, violations of the Terms of Service to the fullest extent permissible by the law. </p>
                <p className='text-base break-words text-justify pb-2'>SocketJuice reserves the right, at any time and without prior notice, in accordance with applicable law, to remove or disable access to any content that SocketJuice, at its sole discretion, considers to be objectionable for any reason, in violation of these Terms, or otherwise harmful to the Services or our community. If we believe you are abusing SocketJuice, our users, or any other person in any way or violating the letter or spirit of any of these Terms, we may, in our sole discretion and without limiting other remedies, limit, suspend, or terminate your SocketJuice Account and access to the Services, remove hosted content, deny a damage claim, remove or demote your listings, reduce or eliminate any discounts, and take technical and/or legal steps to prevent you from using the Services. Additionally, we reserve the right to refuse or terminate access to the Services to anyone for any reason at our discretion to the full extent permitted under applicable law. </p>
                <p className='text-base break-words text-justify pb-2'> When an issue arises, we may consider the user’s performance history and the specific circumstances in applying our Policies. We may choose to be more lenient with policy enforcement in an effort to do the right thing, subject to our sole and absolute discretion. </p>
                <p className='text-base break-words text-justify pb-2'> You agree that SocketJuice may contact you by electronic means (e.g., electronic mail; SMS text messaging, notifications via SocketJuice messaging; app notification) in lieu of any requirement for mailed notices, subject to standard provider charges. To contact you more efficiently, you agree that we may at times also contact you using autodialed or prerecorded message calls or text messages at your phone number(s). We may place such calls or texts to confirm your signup, provide notices regarding your SocketJuice Account or SocketJuice Account activity, investigate or prevent fraud, collect a debt owed to us or recover unpaid invoices, or communicate urgent messages. We may share your phone number(s) with service providers with whom we contract to assist us in pursuing these interests. We will not share your phone number(s) with third parties for their own purposes without your consent. Where SocketJuice is required to obtain your consent for such communications, you may choose to revoke your consent. You agree that SocketJuice may contact you on any day, at any time of day, and in relation with the above purposes. </p>
                <p className='text-base break-words text-justify pb-2'>You authorize SocketJuice and our service providers, without further notice, to monitor or record telephone conversations or web chat interactions you have, or anyone acting on your behalf has, with SocketJuice or its agents for quality control, training, or other purposes. You understand and agree that your communications with SocketJuice may be overheard, monitored, or recorded. If you do not wish to have your call recorded, please contact us instead by emailing us at support@socketjuice.com. If you do not wish to have your chat activity recorded or monitored, please do not use the chat function on the Services. </p>

                <p className='text-center text-xl font-semibold pt-2'> Specific terms for drivers </p>
                <p className='text-base break-words text-justify pb-2'>As a driver reserving charging equipment, you commit that you will be a legally licensed driver and provide proof to the host or via the Services upon request. You agree to handle all charging equipment with care and will take all reasonable measures to return the charging equipment and any other equipment such as adapters on time following completion of the charging reservation and in essentially the same condition as received. You will not allow anyone other than a person listed in the reservation details to handle the charging equipment that you booked. </p>
                <p className='text-center text-lg font-semibold pt-2'> Driver financial responsibility for physical damage to charging equipment</p>
                <p className='text-base break-words text-justify pb-2'>The driver that booked the reservation is financially responsible for all physical damage to charging equipment or theft of charging equipment that occurs during a reservation, plus any additional costs and fees resulting from damage of any kind to the charging equipment, regardless of who is found to be at fault. </p>
                <p className='text-base break-words text-justify pb-2'>Drivers may be insured against damage to the booked charging equipment under their own automobile policies. When you book charging equipment on SocketJuice, you agree that if any damage occurs to the charging equipment during the booked reservation, you will work with SocketJuice to make a claim for coverage under any policy of insurance that applies to the loss. </p>
                <p className='text-center text-lg font-semibold pt-2'>Condition of the charging equipment</p>
                <p className='text-base break-words text-justify pb-2'>You understand that third parties own the charging equipment and related accessories offered through the Services. Each host is responsible for complying with all legal requirements and maintaining their charging equipment in safe condition. Please complete a visual inspection before you begin your use of the charging equipment. If you find damage in your initial inspection, you should upload photos of such pre-existing damage at the start of your reservation to ensure you are not held responsible for pre-existing damage. If you find damage on your initial inspection and fail to report it, SocketJuice, third-party administrators, or insurance partners, may assume that the damage occurred during your reservation period. If, after your initial inspection, you believe that the charging equipment is not safe to use, please do not use the charging equipment; instead, please contact the SocketJuice team immediately. </p>

                <p className='text-center text-lg font-semibold pt-2'> No responsibility for personal belongings </p>
                <p className='text-base break-words text-justify pb-2'>You also acknowledge and agree that neither SocketJuice nor hosts are responsible for lost or stolen property left in the driver’s vehicle or taken or damaged during a reservation. </p>
                <p className='text-center text-lg font-semibold pt-2'> Theft of charging equipment</p>
                <p className='text-base break-words text-justify pb-2'>The following conduct may result in the reporting of charging equipment as stolen to law enforcement, possibly subjecting you and any other driver to arrest, and civil and/or criminal penalties, including but not limited to: (1) If the charging equipment is not returned to the host by the end of the reservation period and you have not properly obtained an extension of the reservation through the Services. (2) If you fail or refuse to communicate in good faith with the host, police, SocketJuice, or other authorities with a full report of any accident or vandalism involving the charging equipment or otherwise fail to cooperate in the investigation of any accident or vandalism, (3) If the vehicle being charged by the booked charging equipment is operated by anyone who has given a fictitious name, false address, or a false or invalid driver’s license, or invalid license plate, or fictitious license plate or whose driver’s license becomes invalid during the reservation period, who has obtained the keys without permission of the host, or who misrepresents or withholds facts to/from the host or SocketJuice material to the reservation.</p>
                <p className='text-base break-words text-justify pb-2'>The primary driver who books the reservation is responsible for any private investigation costs that SocketJuice deems necessary to recover charging equipment that is not returned. In addition, a USD $1,000.00 case administration fee will be imposed on the primary driver if SocketJuice and/or the host has to report charging equipment as stolen to law enforcement due to it not being returned. </p>
                <p className='text-center text-xl font-semibold pt-2'> Specific terms for hosts </p>
                <p className='text-base break-words text-justify pb-2'> As a host, you commit that you will provide safely operating charging equipment, in good mechanical condition. You will provide such charging equipment on time but only to a driver who is listed on the Services for the reservation. Other than what is required for you to verify the license (confirm the license plate matches the reservation and the individual’s identification), you will not collect any information or documentation from your driver at check-in. You commit that your charging equipment listing will be complete and accurate and you will honor all representations made in your listing, including the plug type and charging level. You will not cancel a booking for the purpose of seeking a higher price from a driver. </p>
                <p className='text-base break-words text-justify pb-2'> You will not offer any charging equipment or optional accessories (e.g. adapters) that you do not yourself own or have authority to share or that may not be shared for compensation pursuant to the terms and conditions of any agreement. You will not offer any charging equipment that is the subject of a safety recall without first properly addressing the matter subject to the recall. You will not offer charging equipment that is not legal in the location where it is shared, and it will not have any illegal modifications to any part of the charging equipment. You will remove any hazardous items or other weapons in the immediate vicinity of the charging equipment prior to providing it to a driver. </p>
                <p className='text-center text-lg font-semibold pt-2'>Charging equipment information given at listing; listing conditions</p>
                <p className='text-base break-words text-justify pb-2'>You may only use the Services in connection with charging equipment that you own or otherwise have all the necessary rights and permissions to share for compensation. If the charging equipment you list on the Services is enabled with a device or OEM technology capable of collecting user data, location data, telematics data, disabling technology, or image capturing you agree to comply with all applicable law regarding tracking of user data. </p>
                <p className='text-center text-lg font-semibold pt-2'> SocketJuice photography</p>
                <p className='text-base break-words text-justify pb-2'>Hosts will be required to upload photographs of their charging equipment (“Images”). You alone are responsible for using the Images in connection with your SocketJuice listing and you agree that you will cease using the Images if they no longer accurately represent your charging equipment. You agree that SocketJuice is the sole and exclusive owner - or exclusive licensee, as allowed by applicable law - of all right, title, and interest in all copyrights, trademark rights, and any and all other intellectual property rights, including right of publicity, worldwide, in the Images regardless of whether you include them in your listing, and you shall take no action to challenge or object to the validity of such rights or SocketJuice’s ownership or registration thereof. You acknowledge that SocketJuice may use the Images for advertising, marketing, commercial, and other business purposes in any media or platform, whether in relation to your listing or otherwise, without further notice or compensation. Further, you waive any and all rights to royalties or moral rights you may have in the Images. If you use the SocketJuice photography program, you agree that you will not use the Images in connection with sharing your charging equipment on any platform, website, or application other than SocketJuice. At SocketJuice’s request, you will execute documents and take such further acts as SocketJuice may reasonably request to assist SocketJuice to acquire, perfect, and maintain its intellectual property rights and other legal protection in the Images. </p>
                <p className='text-center text-lg font-semibold pt-2'>Charging equipment availability</p>
                <p className='text-base break-words text-justify pb-2'>Once a reservation is booked, you must make the charging equipment available as expected by the driver. You must supply the location of the charging equipment accurately on SocketJuice and ensure that the charging equipment is available at that location at the beginning of the reservation period. Prior to handing over charging equipment to the driver, hosts will take the necessary steps to verify the driver’s identification and the driver vehicle’s identification to confirm information matches with the booked reservation. </p>
                <p className='text-center text-lg font-semibold pt-2'> Pricing, earnings, and payments</p>
                <p className='text-base break-words text-justify pb-2'> You will have the ability to set and revise the charging equipment’s pricing as you choose. SocketJuice will pay you the amount collected from drivers that book your charging equipment, less the applicable fees payable to SocketJuice. To the extent you owe SocketJuice money for any reason, SocketJuice also reserves the right to deduct those amounts from your earnings payment, debit your bank account, charge any of your payment methods on file, and/or send you an invoice. </p>
                <p className='text-base break-words text-justify pb-2'> In some countries, payment processing services are provided by PayPal and subject to the PayPal User Agreement and the Paypal Terms of Service, which may be modified from time to time. You also agree that SocketJuice is not liable in cases where PayPal processes a payment late or makes a mistake relating to a payment or a payment hold. As a condition of SocketJuice enabling payment processing services through PayPal, you authorize SocketJuice to obtain all necessary access and perform all necessary activity with PayPal. You further agree to provide accurate, complete, and updated information about you to SocketJuice and PayPal. You acknowledge that SocketJuice and PayPal are unrelated entities. You are responsible for separately updating SocketJuice and PayPal when there are material changes to the information you have previously provided (e.g., name, tax information, contact information). You authorize SocketJuice to share such information and transaction information with PayPal for the purposes of facilitating the payment processing services provided by PayPal. SocketJuice reserves the right to switch payment processing vendors at its discretion. </p>
                <p className='text-center text-lg font-semibold pt-2'> Maintenance and Charging Equipment Upkeep </p>
                <p className='text-base break-words text-justify pb-2'>You are required to regularly check your charging equipment for any defects in its operations or safety. You promise that, at all times, your charging equipment will be in safe and operating condition, in good mechanical condition, and in full compliance with all applicable requirements, including any required safety inspections. You agree to respond to any applicable recall or similar safety notices and to complete any recommended action before allowing your charging equipment to be booked. In addition, if SocketJuice believes that your charging equipment does not conform to reasonable standards, SocketJuice may notify you and reserves the right to remove or decline listing your charging equipment until its concerns have been resolved. SocketJuice may, but does not commit to, undertake efforts to ensure the safety of vehicles booked through the Services. </p>
                <p className='text-center text-lg font-semibold pt-2'> Reporting damage</p>
                <p className='text-base break-words text-justify pb-2'>If you believe that a driver has caused any damage to your charging equipment or other property, you are required to report that damage as soon as you become aware of it (and in any event, no more than 24 hours after the scheduled end of the reservation) and to provide reasonable cooperation in the investigation of the damage. Based on the investigation, SocketJuice or third-party claims administrators will reasonably determine whether the damage occurred during the reservation period and whether the situation is eligible for further action including compensation from the driver. If SocketJuice is not given prompt notice as described in this paragraph, or if you do not provide reasonable cooperation in the investigation by SocketJuice or third-party claims administrators, we may not be able to determine the cause. In that case, you agree that we may decline any further action for such damage. You agree to waive SocketJuice from any damage to charging equipment or other property caused during a reservation or related to a reservation. </p>
                <p className='text-center text-xl font-semibold pt-2'> General provisions</p>
                <p className='text-center text-xl font-semibold pt-2'> Termination of Services</p>
                <p className='text-base break-words text-justify pb-2'>You may discontinue your use of the Services at any time and SocketJuice may terminate your access to the Services and remove any listings for any reason or no reason to the extent permissible under applicable law. Termination of access to the Services will not release a Party from any obligations it incurred prior to the termination and SocketJuice may retain and continue to use any information, including but not limited to photography, previously provided by you. Termination of access to the Services will not have any effect on the disclaimers, waiver or liability limitations, or legal disputes provisions and/or any fees due, and all of those terms will survive any termination of access to the Services. </p>
                <p className='text-center text-xl font-semibold pt-2'> No charging equipment transfer or assignment</p>
                <p className='text-base break-words text-justify pb-2'>Except as otherwise provided herein, drivers and hosts agree that nothing in these Terms constitutes an actual or purported transfer or assignment of any right or interest in charging equipment or optional Extras shared through the Services. </p>
                <p className='text-center text-xl font-semibold pt-2'>Disclaimers </p>
                <p className='text-base break-words text-justify pb-2'> SOCKETJUICE PROVIDES SERVICES THAT ENABLE THE SHARING OF CHARGING EQUIPMENT AND OPTIONAL EXTRAS BETWEEN HOSTS AND DRIVERS. EXCEPT AS OTHERWISE PROVIDED IN THESE TERMS, SOCKETJUICE DOES NOT ITSELF PROVIDE CHARGING EQUIPMENT SHARING, RENTAL SERVICES, AND/OR INSURANCE SERVICES AND IS NOT RESPONSIBLE FOR ANY OF THE ACTS OR OMISSIONS OF ANY OF THE USERS OF ITS SERVICES, THE MANUFACTURER OF THE CHARGING EQUIPMENT OR ANY OPTIONAL EXTRAS, OR ANY THIRD PARTY PROVIDER OF CHARGING EQUIPMENT SERVICES. THE SERVICES ARE PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE EXTENT PERMITTED BY APPLICABLE LAW, WITHOUT LIMITING THE FOREGOING, SOCKETJUICE EXPLICITLY DISCLAIMS ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. SocketJuice makes no warranty that the Services, including, but not limited to, the listing and/or any charging equipment or related accessory, will meet your requirements or be available on an uninterrupted, secure, or error-free basis. SocketJuice makes no warranty regarding the quality of any listings, charging equipment, hosts, drivers, the Services, or any content or the accuracy, timeliness, truthfulness, completeness, or reliability of any content obtained through the Services. No advice or information, whether oral or written, obtained from SocketJuice, or its service providers or through the Services or content, will create any warranty not expressly made herein. </p>
                <p className='text-center text-xl font-semibold pt-2'> Limitation of liability and waiver</p>
                <p className='text-base break-words text-justify pb-2'> EXCEPT WHERE PROHIBITED BY LAW, YOU WAIVE AND DISCHARGE ANY AND ALL RIGHTS YOU HAVE TO SUE OR MAKE CLAIMS AGAINST SOCKETJUICE AND ANY OF ITS SUBSIDIARIES, DIRECTORS, OFFICERS, AGENTS (INCLUDING THIRD-PARTY ADMINISTRATORS, INSURANCE PRODUCERS, AND INSURANCE PROVIDERS), OR EMPLOYEES (TOGETHER, THE “SOCKETJUICE PARTIES”) AND ANY SOCKETJUICE USER FOR ANY DAMAGES OR LOSSES, WHETHER DUE TO NEGLIGENCE OR OTHERWISE, ARISING OUT OF OR IN CONNECTION WITH THE FOLLOWING: (1) CHARGING EQUIPMENT AVAILABILITY (E.G., CHARGING EQUIPMENTNOT BEING AVAILABLE OR RETURNED WHEN IT WAS SUPPOSED TO BE), (2) PROBLEMS WITH CHARGING EQUIPMENT(E.G., ANY MALFUNCTION OF OR DEFICIENCY WITH CHARGING EQUIPMENT), (3) CHARGING EQUIPMENT WARRANTY ISSUES (E.G., ANY BREACH OF WARRANTY OR OTHER OBLIGATION BY ANY MANUFACTURER OR OTHER THIRD PARTY ASSOCIATED WITH THE CHARGING EQUIPMENT), (4) THE LEGAL OR LICENSE STATUS OF CHARGING EQUIPMENT, (5) THIRD PARTY ASSESSMENTS OF A CHARGING EQUIPMENT'S VALUE, OR (6) ANY ACTION OR INACTION OF A HOST OR DRIVER. </p>
                <p className='text-base break-words text-justify pb-2'>YOU AGREE THAT NEITHER SOCKETJUICE NOR ANY OTHER PARTY INVOLVED IN CREATING, PRODUCING, OR DELIVERING THE SERVICES WILL BE LIABLE FOR ANY INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING LOST PROFITS, DATA, OR GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE, OR THE COST OF SUBSTITUTE PRODUCTS OR SERVICES), WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY, OR ANY OTHER LEGAL THEORY, ARISING OUT OF OR CONNECTION WITH THE SERVICES (INCLUDING LISTING OR BOOKING OF ANY CHARGING EQUIPMENT OR OPTIONAL EXTRA VIA THE SERVICES), OR THE INABILITY TO USE THE SERVICES. </p>
                <p className='text-base break-words text-justify pb-2'>Except for our obligations to pay amounts to applicable hosts or drivers pursuant to these Terms, including an approved payment request, in no event will the SocketJuice Parties' aggregate liability arising out of or in connection with your use of the Services, exceed the greater of (1) the amounts you have paid or owe for bookings via the Services as a driver in the twelve month period prior to the event giving rise to the liability, or if you are a host, the amount earned by you in the 12 month period prior to the event giving rise to the liability, or (2) US$100. </p>
                <p className='text-base break-words text-justify pb-2'>EXCEPT WHERE PROHIBITED BY LAW, YOU ALSO WAIVE AND DISCHARGE ANY AND ALL RIGHTS YOU HAVE TO SUE OR MAKE CLAIMS AGAINST ANY SOCKETJUICE USER FOR ANY DAMAGES OR LOSSES ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICES. </p>
                <p className='text-base break-words text-justify pb-2'>YOU WAIVE CALIFORNIA CIVIL CODE §1542, OR ANY SIMILAR LAW, WHICH STATES: “A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM OR HER MUST HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR.” </p>
                <p className='text-base break-words text-justify pb-2'>THE ABOVE LIMITATIONS OF LIABILITY AND WAIVER PROVISIONS ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN SOCKETJUICE AND YOU. THEY SHALL APPLY TO THE EXTENT PERMITTED BY APPLICABLE LAW, AND ANY ASPECTS OF THEM THAT ARE DEEMED VOID OR UNENFORCEABLE SHALL BE SEVERED WHILE LEAVING THE REMAINDER IN EFFECT. </p>
                <p className='text-center text-xl font-semibold pt-2'> Indemnification </p>
                <p className='text-base break-words text-justify pb-2'>You agree to release, defend, indemnify, and hold SocketJuice and its subsidiaries, officers, directors, employees, and agents, harmless from and against any claims, liabilities, damages, losses, and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected with: (1) your access to or use of the Services, (2) your violation of these Terms, (3) your user content, (4) your interaction with any other user of the Services, or (5) your booking of charging equipment or creation of a listing for charging equipment. Such indemnification includes but is not limited to any injuries, losses, or damages (compensatory, direct, incidental, consequential, or otherwise) arising in connection with or as a result of a booking, sharing, or use of charging equipment or optional Extra. This indemnification provision is a fundamental element of the basis of the bargain between SocketJuice and you. It shall apply to the extent permitted by applicable law, and any aspects of it that are deemed unenforceable shall be severed while leaving the remainder in effect. </p>
                <p className='text-center text-xl font-semibold pt-2'> Liquidated damages </p>
                <p className='text-base break-words text-justify pb-2'>You acknowledge that the actual damages likely to result from your breaches of the Terms of Service by any of the following are difficult to estimate accurately and would be difficult for SocketJuice to prove with certainty: (1) engaging in gray market transactions, as defined in these Terms, (2) using the SocketJuice domains, trademarks, or taglines without SocketJuice's express consent, including without limitation registering website domains or social media handles, or bidding on online advertising key words, (3) suing or asserting legal claims against the SocketJuice Parties or a SocketJuice user in any manner prohibited or waived herein, (4) as a host, offering charging equipment that is not the property of the host, (5) as a host, offering any charging equipment or releasing charging equipment to a driver that is not in operating condition or is otherwise in an unsafe condition, (6) as a host, cancel or modify a reservation to manipulate the price or potential earnings for charging equipment, or (7) creating or using a SocketJuice account that has the effect of circumventing SocketJuice’s suspension, termination, or closure of another SocketJuice account. You will pay SocketJuice $7,500 per breach in Liquidated Damages to compensate SocketJuice for any such conduct. This amount is not intended as a punishment for any such breach, but rather as a reasonable estimate where actual damages are difficult estimate accurately and/or prove with certainty. This liquidated damages provision is a fundamental element of the basis of the bargain between SocketJuice and you. It shall apply to the extent permitted by applicable law, and any aspects of it that are deemed unenforceable shall be severed while leaving the remainder in effect. </p>
                <p className='text-center text-xl font-semibold pt-2'> Not a rental company; no leasing of charging equipment </p>
                <p className='text-base break-words text-justify pb-2'>SocketJuice is not a rental company. It does not own charging equipment and is not in the business of renting charging equipment to the public. SocketJuice also is not providing short- or long-term leases of charging equipment. SocketJuice provides an online platform where owners of charging equipment and those in need of charging equipment can meet and share amongst themselves subject to these Terms. </p>
                <p className='text-center text-xl font-semibold pt-2'> Rounding off; currency </p>
                <p className='text-base break-words text-justify pb-2'>SocketJuice may, in its sole discretion, round up or down amounts that are payable from or to hosts or drivers to the nearest whole functional base unit in which the currency is denominated (e.g. to the nearest cent for dollar, euro, pound, or other supported currency) unless explicitly prohibited under applicable law. The currency displayed on the Services is based on the search location, charging equipment location, and/or host location.</p>
                <p className='text-center text-xl font-semibold pt-2'> Translations </p>
                <p className='text-base break-words text-justify pb-2'> Where SocketJuice has provided you with a translation of the English language version of these Terms or any Policies, in case of any wording discrepancies between the English and any other versions of the Terms and any Policies, the English language wording takes precedence. </p>
                <p className='text-center text-xl font-semibold pt-2'> Severability and non-waiver</p>
                <p className='text-base break-words text-justify pb-2'> In the event any provision of these Terms is held to be void, voidable, or unenforceable, the remaining provisions shall remain in full force and effect. The failure of any Party to enforce any provision of these Terms shall not be construed to be a waiver of such provision, or any other provision, nor in any way to affect the validity of these Terms or any part of these Terms, or any right of any Party to enforce that provision or each and every other provision at any time. No waiver of any breach of these Terms shall constitute or be deemed a waiver of any other breach. </p>
                <p className='text-center text-xl font-semibold pt-2'> General </p>
                <p className='text-base break-words text-justify pb-2'>SocketJuice does not appoint you or any other user as its employee, mandatory, legal agent, or form any kind of legal partnership or joint venture. You are not authorized to make any commitments on behalf of SocketJuice and SocketJuice will not make commitments on your behalf, except as contemplated by the Services or expressly stated in these Terms. </p>
                <p className='text-base break-words text-justify pb-2'>Agreeing to these Terms of Service supersedes any earlier verbal or written communications between us. With the exception of appointing a custodian to manage your charging equipment on your behalf, you may not delegate your legal obligations or transfer any of your rights, in whole or in part, to any third party without advance written consent of SocketJuice. You will remain responsible for your obligations hereunder in any event. A SocketJuice director or officer must agree to any modification or waiver of any item of these Terms of Service in writing. Headings are for reference purposes only and do not limit the scope or extent of such section. </p>
                
            </div>
        </div>
        </>
    )
}