
export const regionData = [
    {region: "Select Region", code:"N/A", country: "N/A"}, 
    {region: "Select All", code:"Select All", country: "Select All"}, 
    {region: "Alabama", code:"AL", country: "United States"}, 
    {region: "Alaska", code:"AK", country: "United States"}, 
    {region: "Arizona", code:"AZ", country: "United States"}, 
    {region: "Arkansas", code:"AR", country: "United States"}, 
    {region: "California", code:"CA", country: "United States"}, 
    {region: "Colorado", code:"CO", country: "United States"}, 
    {region: "Connecticut", code:"CT", country: "United States"}, 
    {region: "Delaware", code:"DE", country: "United States"}, 
    {region: "District of Columbia", code:"DC", country: "United States"}, 
    {region: "Florida", code:"FL", country: "United States"}, 
    {region: "Georgia", code:"GA", country: "United States"}, 
    {region: "Hawaii", code:"HI", country: "United States"}, 
    {region: "Idaho", code:"ID", country: "United States"}, 
    {region: "Illinois", code:"IL", country: "United States"}, 
    {region: "Indiana", code:"IN", country: "United States"}, 
    {region: "Iowa", code:"IA", country: "United States"}, 
    {region: "Kansas", code:"KS", country: "United States"}, 
    {region: "Kentucky", code:"KY", country: "United States"}, 
    {region: "Louisiana", code:"LA", country: "United States"}, 
    {region: "Maine", code:"ME", country: "United States"}, 
    {region: "Maryland", code:"MD", country: "United States"}, 
    {region: "Massachusetts", code:"MA", country: "United States"}, 
    {region: "Michigan", code:"MI", country: "United States"}, 
    {region: "Minnesota", code:"MN", country: "United States"}, 
    {region: "Mississippi", code:"MS", country: "United States"}, 
    {region: "Missouri", code:"MO", country: "United States"}, 
    {region: "Montana", code:"MT", country: "United States"}, 
    {region: "Nebraska", code:"NE", country: "United States"}, 
    {region: "Nevada", code:"NV", country: "United States"}, 
    {region: "New Hampshire", code:"NH", country: "United States"}, 
    {region: "New Jersey", code:"NJ", country: "United States"}, 
    {region: "New Mexico", code:"NM", country: "United States"}, 
    {region: "New York", code:"NY", country: "United States"}, 
    {region: "North Carolina", code:"NC", country: "United States"}, 
    {region: "North Dakota", code:"ND", country: "United States"}, 
    {region: "Ohio", code:"OH", country: "United States"}, 
    {region: "Oklahoma", code:"OK", country: "United States"}, 
    {region: "Oregon", code:"OR", country: "United States"}, 
    {region: "Pennsylvania", code:"PA", country: "United States"}, 
    {region: "Rhode Island", code:"RI", country: "United States"}, 
    {region: "South Carolina", code:"SC", country: "United States"}, 
    {region: "South Dakota", code:"SD", country: "United States"}, 
    {region: "Tennessee", code:"TN", country: "United States"}, 
    {region: "Texas", code:"TX", country: "United States"}, 
    {region: "Utah", code:"UT", country: "United States"}, 
    {region: "Vermont", code:"VT", country: "United States"}, 
    {region: "Virginia", code:"VA", country: "United States"}, 
    {region: "Washington", code:"WA", country: "United States"}, 
    {region: "West Virginia", code:"WV", country: "United States"}, 
    {region: "Wisconsin", code:"WI", country: "United States"}, 
    {region: "Wyoming", code:"WY", country: "United States"}, 
    {region: "Newfoundland and Labrador", code:"NL", country: "Canada"}, 
    {region: "Prince Edward Island", code:"PE", country: "Canada"}, 
    {region: "Nova Scotia", code:"NS", country: "Canada"}, 
    {region: "New Brunswick", code:"NB", country: "Canada"}, 
    {region: "Quebec", code:"QC", country: "Canada"}, 
    {region: "Ontario", code:"ON", country: "Canada"}, 
    {region: "Manitoba", code:"MB", country: "Canada"}, 
    {region: "Saskatchewan", code:"SK", country: "Canada"}, 
    {region: "Alberta", code:"AB", country: "Canada"}, 
    {region: "British Columbia", code:"BC", country: "Canada"}, 
    {region: "Yukon", code:"YT", country: "Canada"}, 
    {region: "Northwest Territories", code:"NT", country: "Canada"}, 
    {region: "Nunavut", code:"NU", country: "Canada"}, 
    {region: "North East", code:"UKC", country: "United Kingdom"}, 
    {region: "North West", code:"UKD", country: "United Kingdom"}, 
    {region: "Yorkshire and the Humber", code:"UKE", country: "United Kingdom"}, 
    {region: "East Midlands", code:"UKF", country: "United Kingdom"}, 
    {region: "West Midlands", code:"UKG", country: "United Kingdom"}, 
    {region: "East of England", code:"UKH", country: "United Kingdom"}, 
    {region: "Greater London", code:"UKI", country: "United Kingdom"}, 
    {region: "South East", code:"UKJ", country: "United Kingdom"}, 
    {region: "South West", code:"UKK", country: "United Kingdom"}, 
    {region: "Wales", code:"UKL", country: "United Kingdom"}, 
    {region: "Scotland", code:"UKM", country: "United Kingdom"}, 
    {region: "Northern Ireland", code:"UKN", country: "United Kingdom"}, 
    {region: "New South Wales", code:"NSW", country: "Australia"}, 
    {region: "Northern Territory", code:"NT", country: "Australia"}, 
    {region: "Queensland", code:"QLD", country: "Australia"}, 
    {region: "South Australia", code:"SA", country: "Australia"}, 
    {region: "Tasmania", code:"TAS", country: "Australia"}, 
    {region: "Victoria", code:"VIC", country: "Australia"}, 
    {region: "Western Australia", code:"WA", country: "Australia"}, 
    {region: "Aichi", code:"JPACH", country: "Japan"}, 
    {region: "Akita", code:"JPAKT", country: "Japan"}, 
    {region: "Aomori", code:"JPAMR", country: "Japan"}, 
    {region: "Chiba", code:"JPCHB", country: "Japan"}, 
    {region: "Ehime", code:"JPEHM", country: "Japan"}, 
    {region: "Fukuoka", code:"JPFKK", country: "Japan"}, 
    {region: "Fukushima", code:"JPFKS", country: "Japan"}, 
    {region: "Fukui", code:"JPFUK", country: "Japan"},
    {region: "Gifu", code:"JPGIF", country: "Japan"},
    {region: "Gunma", code:"JPGUM", country: "Japan"},
    {region: "Hokkaido", code:"JPHKD", country: "Japan"},
    {region: "Hiroshima", code:"JPHRS", country: "Japan"},
    {region: "Hyogo", code:"JPHYG", country: "Japan"},
    {region: "Ibaraki", code:"JPIBR", country: "Japan"},
    {region: "Ishikawa", code:"JPISK", country: "Japan"},
    {region: "Iwate", code:"JPIWT", country: "Japan"},
    {region: "Kagoshima", code:"JPKGS", country: "Japan"},
    {region: "Kagawa", code:"JPKGW", country: "Japan"},
    {region: "Kumamoto", code:"JPKMM", country: "Japan"},
    {region: "Kanagawa", code:"JPKNG", country: "Japan"},
    {region: "Kochi", code:"JPKOC", country: "Japan"},
    {region: "Kyoto", code:"JPKYT", country: "Japan"},
    {region: "Mie", code:"JPMIE", country: "Japan"},
    {region: "Miyagi", code:"JPMYG", country: "Japan"},
    {region: "Miyazaki", code:"JPMYZ", country: "Japan"},
    {region: "Nara", code:"JPNAR", country: "Japan"},
    {region: "Nagano", code:"JPNGN", country: "Japan"},
    {region: "Nagasaki", code:"JPNGS", country: "Japan"},
    {region: "Niigata", code:"JPNGT", country: "Japan"},
    {region: "Oita", code:"JPOIT", country: "Japan"},
    {region: "Okinawa", code:"JPOKN", country: "Japan"},
    {region: "Okayama", code:"JPOKY", country: "Japan"},
    {region: "Osaka", code:"JPOSK", country: "Japan"},
    {region: "Saga", code:"JPSAG", country: "Japan"},
    {region: "Shiga", code:"JPSHG", country: "Japan"},
    {region: "Shimane", code:"JPSMN", country: "Japan"},
    {region: "Saitama", code:"JPSTM", country: "Japan"},
    {region: "Shizuoka", code:"JPSZO", country: "Japan"},
    {region: "Tochigi", code:"JPTCG", country: "Japan"},
    {region: "Tottori", code:"JPTGR", country: "Japan"},
    {region: "Tokushima", code:"JPTKS", country: "Japan"},
    {region: "Tokyo", code:"JPTOK", country: "Japan"},
    {region: "Toyama", code:"JPTYM", country: "Japan"},
    {region: "Wakayama", code:"JPWKY", country: "Japan"},
    {region: "Yamaguchi", code:"JPYMG", country: "Japan"},
    {region: "Yamanashi", code:"JPYMN", country: "Japan"},
    {region: "Yamagata", code:"JPYMT", country: "Japan"},
    {region: "Northland", code:"NZNTL", country: "New Zealand"},
    {region: "Auckland", code:"NZAUK", country: "New Zealand"},
    {region: "Waikato", code:"NZWKO", country: "New Zealand"},
    {region: "Bay of Plenty", code:"NZBOP", country: "New Zealand"},
    {region: "Gisborne", code:"NZGIS", country: "New Zealand"},
    {region: "Hawke's Bay", code:"NZHKB", country: "New Zealand"},
    {region: "Taranaki", code:"NZTKI", country: "New Zealand"},
    {region: "Manawatū-Whanganui", code:"NZMWT", country: "New Zealand"},
    {region: "Wellington", code:"NZWGN", country: "New Zealand"},
    {region: "Tasman", code:"NZTAS", country: "New Zealand"},
    {region: "Nelson", code:"NZNSN", country: "New Zealand"},
    {region: "Marlborough", code:"NZMBH", country: "New Zealand"},
    {region: "West Coast", code:"NZWTC", country: "New Zealand"},
    {region: "Canterbury", code:"NZCAN", country: "New Zealand"},
    {region: "Otago", code:"NZOTA", country: "New Zealand"},
    {region: "Southland", code:"NZSTL", country: "New Zealand"},
    {region: "Munster", code:"IEMUN", country: "Ireland"},
    {region: "Leinster", code:"IELEI", country: "Ireland"},
    {region: "Ulster", code:"IEULS", country: "Ireland"},
    {region: "Connacht", code:"IECON", country: "Ireland"},
];